/**
 * build-client.mjs — 把插件的浏览器半侧打包成 DSH 客户端模块系统可分发的
 * CJS 工厂形态（window.__ModuleLoader__.load({ id, factory })）。
 *
 * 外部依赖 react 由 shell seed 基线提供（bundle 纯净度门禁：
 * 不 value-import 任何 DSH 包）。产物 dist/client.js 由
 * package.json exports["./client"] 指向，供 dsh-client-modules /plugins 路由下发。
 *
 * 用法：node tools/build-client.mjs
 */
import { rolldown } from 'rolldown'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { mkdirSync, readFileSync, statSync } from 'node:fs'

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = join(here, '..')
const input = join(pkgRoot, 'src/client/index.ts')
const outFile = join(pkgRoot, 'dist/client.js')

const BANNER = [
  '// Generated by tools/build-client.mjs \u2014 do not edit.',
  '// Factory-form client half consumed by window.__ModuleLoader__ (lazy CJS).',
  'window.__ModuleLoader__.load({',
  '  id: "dsh-madrank",',
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
].join('\n')

const FOOTER = [
  '    return module.exports;',
  '  }',
  '});',
].join('\n')

const bundle = await rolldown({
  input,
  // react 与 react-dom 均为 shell seed（官方半侧同样 require('react-dom')）
  external: [/^react(-dom)?(\/.+)?$/],
  platform: 'browser',
})

await bundle.write({
  file: outFile,
  format: 'cjs',
  banner: BANNER,
  footer: FOOTER,
})

// Sanity gates: factory envelope present, no bare top-level load, size sane.
const out = readFileSync(outFile, 'utf8')
// 前导可为生成注释；首个非空非注释代码必须进入 factory 信封
const code = out.split('\n').filter((l) => l.trim() !== '' && !l.trim().startsWith('//')).join('\n')
if (!code.startsWith('window.__ModuleLoader__.load({')) {
  throw new Error('banner missing: bundle must open the __ModuleLoader__ factory envelope')
}
if (!code.includes('exports.apply') || !code.includes('exports.inject')) {
  throw new Error('apply/inject exports missing from client half')
}
if (!out.trimEnd().endsWith('});')) {
  throw new Error('footer missing: bundle must end with });')
}
for (const banned of ['node:fs', 'node:path', 'process.env']) {
  if (out.includes(banned)) throw new Error('host-only reference leaked into client half: ' + banned)
}
const bytes = statSync(outFile).size

mkdirSync(dirname(outFile), { recursive: true })
console.log('[build-client] wrote', outFile, bytes, 'bytes')

const pkgPath = join(pkgRoot, 'package.json')
console.log('[build-client] remember: package.json exports["./client"] -> ./dist/client.js')

